### ISSUE TITLE
Both sensor.sensordata_without_correction and chemicals.boreholes_time_series_without_chemicals are shown always 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/watsonc#43]
One layer is selected:
![image](https://user-images.githubusercontent.com/3850918/59340538-7b550380-8d06-11e9-8b10-86e980aa2801.png)

Both layers are rendered:
![image](https://user-images.githubusercontent.com/3850918/59340717-cf5fe800-8d06-11e9-832c-79d407cfad0c.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/watsonc/commit/ce19a8e24535c92d0754d6205409762cd7096126

**Comment by mapcentia** [comment]
Both layers are still getting SVG symbols when switching on only one:

![Peek 2019-06-12 21-01](https://user-images.githubusercontent.com/3850918/59378760-5d62bf80-8d55-11e9-8abe-0b1139cd956b.gif)

**Comment by sashuk** [comment]
@mapcentia Seems like the SQL queries are correct for "v:sensor.sensordata_with_correction,sensor.sensordata_without_correction", but the result returned always includes the "sensordata" features, which is not correct. Could you please specify if there were any changes to the tables or views made that could possibly influence the output?

![watsonc2](https://user-images.githubusercontent.com/1390758/59487060-189e6c00-8eae-11e9-8592-e4378737c52b.gif)

**Comment by sashuk** [comment]
@mapcentia @JacobBirk Seems like the SQL queries are correct for "v:sensor.sensordata_with_correction,sensor.sensordata_without_correction", but the result returned always includes the "sensordata" features, which is not correct. Could you please specify if there were any changes to the tables or views made that could possibly influence the output?

I've checked the `chemicals.boreholes_time_series_with_chemicals` View definition and it seems correct, maybe the data from `sensor.sensordata_with_correction` is duplicated in the `chemicals.boreholes_time_series_with_chemicals` as well? 

![watsonc2](https://user-images.githubusercontent.com/1390758/59487060-189e6c00-8eae-11e9-8592-e4378737c52b.gif)

**Comment by sashuk** [comment]
@mapcentia Could you please check if the issue is fixed now? Just tried your example, seems like data is displayed correctly:

![watsonc2](https://user-images.githubusercontent.com/1390758/59600140-f5d0b980-9132-11e9-8340-b5d798ef58f6.gif)

When two boreholes are located at the same location, the tabbed view is available:

![watsonc](https://user-images.githubusercontent.com/1390758/59600243-421bf980-9133-11e9-9852-76e9fc7a7f16.gif)

Reference link: https://vidi.alexshumilov.ru/app/jupiter/chemicals/?tmpl=watsonc.tmpl#osm/15/9.9156/57.0374/v:chemicals.boreholes_time_series_with_chemicals,sensor.sensordata_without_correction,chemicals.boreholes_time_series_without_chemicals

**Comment by mapcentia** [comment]
@sashuk Seems to work. Closing
